// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMoYk6Ozy5uvCPSMJL5_M9XPmm30sugmw',
    appId: '1:1092746208662:web:95b9f5bbb17a5ab00d69b7',
    messagingSenderId: '1092746208662',
    projectId: 'build-resume-b2934',
    authDomain: 'build-resume-b2934.firebaseapp.com',
    storageBucket: 'build-resume-b2934.appspot.com',
    measurementId: 'G-2SDQTT5TSG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9P-bvWEIimnMxasKxR8CWNj-Nnptgy18',
    appId: '1:1092746208662:android:73be6b6230820a250d69b7',
    messagingSenderId: '1092746208662',
    projectId: 'build-resume-b2934',
    storageBucket: 'build-resume-b2934.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKd3eEeWsdg8Hzi9K-GGqJMAwdttgb56E',
    appId: '1:1092746208662:ios:cc46b88b3ac323390d69b7',
    messagingSenderId: '1092746208662',
    projectId: 'build-resume-b2934',
    storageBucket: 'build-resume-b2934.appspot.com',
    iosClientId: '1092746208662-bqgh5tqnvr38ffsvos953e4dr0e6e0j6.apps.googleusercontent.com',
    iosBundleId: 'com.example.buildResume',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKd3eEeWsdg8Hzi9K-GGqJMAwdttgb56E',
    appId: '1:1092746208662:ios:cc46b88b3ac323390d69b7',
    messagingSenderId: '1092746208662',
    projectId: 'build-resume-b2934',
    storageBucket: 'build-resume-b2934.appspot.com',
    iosClientId: '1092746208662-bqgh5tqnvr38ffsvos953e4dr0e6e0j6.apps.googleusercontent.com',
    iosBundleId: 'com.example.buildResume',
  );
}
